version: "3.8"

x-xgc-image: &xgc-image
  image: xgc_erpnext:v16  # built from ./Dockerfile

x-depends-on-configurator: &depends-on-configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

services:
  configurator:
    <<: *xgc-image
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: [bash, -c]
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host mariadb;
        bench set-config -gp db_port 3306;
        bench set-config -g redis_cache "redis://redis-cache:6379";
        bench set-config -g redis_queue "redis://redis-queue:6379";
        bench set-config -gp socketio_port 9000;
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - frappe-network

  backend:
    <<: [*xgc-image, *depends-on-configurator]
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-network

  frontend:
    <<: *depends-on-configurator
    image: frappe/erpnext:v16.latest
    command: [nginx-entrypoint.sh]
    environment:
      - BACKEND=backend:8000
      - FRAPPE_SITE_NAME_HEADER=${FRAPPE_SITE_NAME_HEADER:-$$host}
      - SOCKETIO=websocket:9000
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE=off
      - PROXY_READ_TIMEOUT=120
      - CLIENT_MAX_BODY_SIZE=50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - frappe-network
    ports:
      - "8080:8080"

  websocket:
    <<: *depends-on-configurator
    image: frappe/erpnext:v16.latest
    command: [node, /home/frappe/frappe-bench/apps/frappe/socketio.js]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
      - frappe-network

  queue-short:
    <<: [*xgc-image, *depends-on-configurator]
    deploy:
      restart_policy:
        condition: on-failure
    command: [bench, worker, --queue, short,default]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-network

  queue-long:
    <<: [*xgc-image, *depends-on-configurator]
    deploy:
      restart_policy:
        condition: on-failure
    command: [bench, worker, --queue, long,default,short]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-network

  scheduler:
    <<: [*xgc-image, *depends-on-configurator]
    deploy:
      restart_policy:
        condition: on-failure
    command: [bench, schedule]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-network

  mariadb:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - frappe-network

  redis-cache:
    image: redis:7-alpine
    volumes:
      - redis-cache-data:/data
    networks:
      - frappe-network

  redis-queue:
    image: redis:7-alpine
    volumes:
      - redis-queue-data:/data
    networks:
      - frappe-network

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe-network:
    driver: bridge
