#!/bin/bash
# Script to rebuild Frappe assets in Docker

echo "🔧 Rebuilding Frappe/ERPNext assets..."

# Option 1: If you can exec into the container
echo ""
echo "Run these commands in your Docker container:"
echo ""
echo "# Enter your Frappe container"
echo "docker exec -it <container-name> bash"
echo ""
echo "# Navigate to bench directory (usually /workspace/frappe-bench or /home/frappe/frappe-bench)"
echo "cd /workspace/frappe-bench  # or wherever your bench is"
echo ""
echo "# Clear cache"
echo "bench clear-cache"
echo ""
echo "# Rebuild all assets with force flag"
echo "bench build --force"
echo ""
echo "# Or rebuild specific apps"
echo "bench build --app frappe"
echo "bench build --app erpnext"
echo "bench build --app xgc_theme"
echo ""
echo "# Restart bench"
echo "bench restart"
echo ""
echo "---"
echo ""
echo "If bench build fails, try:"
echo "rm -rf */public/dist"
echo "rm -rf sites/assets"
echo "bench build --force"
