/**
 * BackstopJS Configuration for XGC Theme Visual Regression Testing
 * 
 * This configuration defines visual regression test scenarios for:
 * - Desk interface (sidebar, toolbar, forms, lists)
 * - Website interface (header, content, forms)
 * - Light and dark theme variants
 * - Responsive breakpoints (mobile, tablet, desktop)
 * 
 * Requirements: 11.5, 6.1, 6.2, 6.3, 7.1, 7.2, 7.3, 8.1, 8.2
 */

module.exports = {
  id: "xgc_theme_visual_regression",
  viewports: [
    {
      label: "mobile",
      width: 320,
      height: 568
    },
    {
      label: "tablet",
      width: 768,
      height: 1024
    },
    {
      label: "desktop",
      width: 1920,
      height: 1080
    }
  ],
  onBeforeScript: "puppet/onBefore.js",
  onReadyScript: "puppet/onReady.js",
  scenarios: [
    // ===== Desk Interface Scenarios =====
    {
      label: "Desk - Sidebar Navigation (Light)",
      url: "http://localhost:8000/app",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".desk-sidebar",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".desk-sidebar"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Desk - Sidebar Navigation (Dark)",
      url: "http://localhost:8000/app",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".desk-sidebar",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".desk-sidebar"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    {
      label: "Desk - Toolbar and Page Header (Light)",
      url: "http://localhost:8000/app",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".page-head",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".page-head"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Desk - Toolbar and Page Header (Dark)",
      url: "http://localhost:8000/app",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".page-head",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".page-head"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    {
      label: "Desk - Form View (Light)",
      url: "http://localhost:8000/app/user",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".frappe-control",
      delay: 1500,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: ["document"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Desk - Form View (Dark)",
      url: "http://localhost:8000/app/user",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".frappe-control",
      delay: 1500,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: ["document"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    {
      label: "Desk - List View (Light)",
      url: "http://localhost:8000/app/user",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".grid-row",
      delay: 1500,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".page-content"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Desk - List View (Dark)",
      url: "http://localhost:8000/app/user",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".grid-row",
      delay: 1500,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".page-content"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    
    // ===== Website Interface Scenarios =====
    {
      label: "Website - Header and Navigation (Light)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-header",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-header"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Website - Header and Navigation (Dark)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-header",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-header"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    {
      label: "Website - Content Area (Light)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-content",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-content"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Website - Content Area (Dark)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-content",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-content"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    {
      label: "Website - Form (Light)",
      url: "http://localhost:8000/contact",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-form",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-form"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true
    },
    {
      label: "Website - Form (Dark)",
      url: "http://localhost:8000/contact",
      referenceUrl: "",
      readyEvent: "",
      readySelector: ".web-form",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: [".web-form"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      onBeforeScript: "puppet/setDarkTheme.js"
    },
    
    // ===== Responsive Breakpoint Scenarios =====
    {
      label: "Responsive - Mobile Layout (Light)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: "body",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: ["document"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      viewports: [{ label: "mobile", width: 320, height: 568 }]
    },
    {
      label: "Responsive - Tablet Layout (Light)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: "body",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: ["document"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      viewports: [{ label: "tablet", width: 768, height: 1024 }]
    },
    {
      label: "Responsive - Desktop Layout (Light)",
      url: "http://localhost:8000",
      referenceUrl: "",
      readyEvent: "",
      readySelector: "body",
      delay: 1000,
      hideSelectors: [],
      removeSelectors: [],
      hoverSelector: "",
      clickSelector: "",
      postInteractionWait: 0,
      selectors: ["document"],
      selectorExpansion: true,
      expect: 0,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
      viewports: [{ label: "desktop", width: 1920, height: 1080 }]
    }
  ],
  paths: {
    bitmaps_reference: "tests/visual/backstop_data/bitmaps_reference",
    bitmaps_test: "tests/visual/backstop_data/bitmaps_test",
    engine_scripts: "tests/visual/backstop_data/engine_scripts",
    html_report: "tests/visual/backstop_data/html_report",
    ci_report: "tests/visual/backstop_data/ci_report"
  },
  report: ["browser"],
  engine: "puppeteer",
  engineOptions: {
    args: ["--no-sandbox"]
  },
  asyncCaptureLimit: 5,
  asyncCompareLimit: 50,
  debug: false,
  debugWindow: false
};
